export const data = [
  {
    id: 1,
    image: "https://picsum.photos/160",
    subs: "80k",
    title: "This is java tutoutorials you can learn youtube clone here",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/170",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 2,
    image: "https://picsum.photos/280",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/280`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 3,
    image: "https://picsum.photos/170",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/170",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 4,
    image: "https://picsum.photos/260",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/260",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 5,
    image: "https://picsum.photos/90",
    subs: "80k",
    title: "Python coding",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/90",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 6,
    image: "https://picsum.photos/480",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/480`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 7,
    image: "https://picsum.photos/270",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/270",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 8,
    image: "https://picsum.photos/60",
    subs: "80k",
    title: "Javascript tutorails",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/60",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 9,
    image: "https://picsum.photos/450",
    subs: "80k",
    title: "React js",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/450",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 10,
    image: "https://picsum.photos/40",
    subs: "80k",
    title: "Photo edit",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/40`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 11,
    image: "https://picsum.photos/30",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/30",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 12,
    image: "https://picsum.photos/120",
    subs: "80k",
    title: "Moon color change",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/110",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 13,
    image: "https://picsum.photos/790",
    subs: "80k",
    title: "About react js",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/790",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 14,
    image: "https://picsum.photos/480",
    subs: "80k",
    title: "Bike stunt",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/480`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 15,
    image: "https://picsum.photos/70",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/70",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 16,
    image: "https://picsum.photos/60",
    subs: "80k",
    title: "New mobiles",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/60",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 17,
    image: "https://picsum.photos/90",
    subs: "80k",
    title: "About react js",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/90",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 18,
    image: "https://picsum.photos/480",
    subs: "80k",
    title: "happy mood songs",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/480`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 19,
    image: "https://picsum.photos/270",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/270",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 20,
    image: "https://picsum.photos/60",
    subs: "80k",
    title: "Comdy videos",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/460",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 21,
    image: "https://picsum.photos/450",
    subs: "80k",
    title: "About react js",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/450",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 22,
    image: "https://picsum.photos/40",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/40`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 23,
    image: "https://picsum.photos/330",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/330",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 24,
    image: "https://picsum.photos/120",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/120",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 25,
    image: "https://picsum.photos/320",
    subs: "80k",
    title: "About react js",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/320",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 26,
    image: "https://picsum.photos/400",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/400`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 27,
    image: "https://picsum.photos/390",
    subs: "80k",
    title: "This is new video for blogs tutorials",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/390",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 28,
    image: "https://picsum.photos/380",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/380",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 29,
    image: "https://picsum.photos/170",
    subs: "80k",
    title: "About react js",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/170",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 30,
    image: "https://picsum.photos/360",
    subs: "80k",
    title: "About react js tutorials",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/360`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 31,
    image: "https://picsum.photos/350",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/350",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 32,
    image: "https://picsum.photos/340",
    subs: "80k",
    title: "Java coding",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/340",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 33,
    image: "https://picsum.photos/330",
    subs: "80k",
    title: "React js tutorials",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/330",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 34,
    image: "https://picsum.photos/120",
    subs: "80k",
    title: "Java coding",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/120`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 35,
    image: "https://picsum.photos/210",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/210",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 36,
    image: "https://picsum.photos/300",
    subs: "80k",
    title: "python tutorials",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/300",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 37,
    image: "https://picsum.photos/290",
    subs: "80k",
    title: "Java coding",
    channel: "Raghu Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/290",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 38,
    image: "https://picsum.photos/80",
    subs: "80k",
    title: "About react js",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: `https://picsum.photos/80`,
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 39,
    image: "https://picsum.photos/170",
    subs: "80k",
    title: "This is new video for blogs",
    channel: "Nayak",
    views: "1.5M Views",
    timeStamp: "3 days ago",
    channelImg: "https://picsum.photos/170",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
  {
    id: 40,
    image: "https://picsum.photos/280",
    subs: "80k",
    title: "python mcq questions",
    channel: "Manju Nayak",
    views: "1M Views",
    timeStamp: "2 days ago",
    channelImg: "https://picsum.photos/280",
    description:
      "This is About react js toutorials you can learn youtube clone here",
  },
];

export const buttonData = [
  {
    id: 1,
    title: "Music",
  },
  {
    id: 2,
    title: "Jukebox",
  },
  {
    id: 3,
    title: "Live",
  },
  {
    id: 4,
    title: "Reactjs",
  },
  {
    id: 5,
    title: "Python",
  },
  {
    id: 6,
    title: "Datas",
  },
  {
    id: 7,
    title: "Movies",
  },
  {
    id: 8,
    title: "Presentation",
  },
  {
    id: 9,
    title: "Watched",
  },
  {
    id: 10,
    title: "Games",
  },
];
